### ISSUE TITLE
Javascript error

### ISSUE THREAD

**Issue by myleslee** [andreasRu/lucee-admin-language-editor#12]
It seems neither Pull from Github or Initialize File works after  the website is up.

![Screenshot 2023-01-18 at 08 36 03](https://user-images.githubusercontent.com/108758/213050978-547d8606-32d7-489d-a27c-ccda77450195.png)

**Comment by andreasRu** [comment]
Thanks for posting the issue. Interresting...Looks like the cfm template of the ajax call is returninga 500 server error when initilizing the language file.

I've updated the latest version with some commits, particluary with:
[56706acd4b3f206c192b4092fc8de6ca46a11d8e](https://github.com/andreasRu/lucee-admin-language-editor/commit/56706acd4b3f206c192b4092fc8de6ca46a11d8e)

Could you please re-download the editor. With that version you should be able to see the CFML error loaded and injected into to the page.

**Comment by myleslee** [comment]
![screencapture-127-0-0-1-62703-2023-01-19-10_14_28](https://user-images.githubusercontent.com/108758/213341026-13ddb9de-890b-4b91-a513-1dfbc491a791.png)

If I copy and paste the link `https://raw.githubusercontent.com/lucee/Lucee/6.0/core/src/main/cfml/context/admin/resources/language/en.xml` into the browser, I'm able to see the content of en.xml though.

**Comment by andreasRu** [comment]
Ok, this is usually thrown if your machine/pc/laptop don't have any internet connection during the pull of the source files, so the https call throws the error. I'm going to fix this with some error handdling. 

Thx for posting!!!

**Comment by andreasRu** [comment]
Could you try the last version, if possible? Thank you.

**Comment by andreasRu** [comment]
This was fixed with 0.0.7. If the problem persists, please reopen the issue

**Comment by andreasRu** [comment]
Closing issue
