### ISSUE TITLE
error: Can't copy file

### ISSUE THREAD

**Issue by guustnieuwenhuis** [andreasRu/lucee-admin-language-editor#13]
# steps to reproduce

* start app
* select dutch resource file (Nederlands nl.xml)
* click "Pull from Lucee at Github"

# error

Lucee 5.3.10.97 Error (application)
--
Message | Can't copy file [https://raw.githubusercontent.com/lucee/Lucee/6.0/core/src/main/cfml/context/admin/resources/language/nl.xml] to [/workingDir/nl.xml]
Detail | No such file or directory
Stacktrace | The Error Occurred in/Users/guustnieuwenhuis/Projects/Playground/lucee-admin-language-editor/webroot/components/LangEditorService.cfc: line 314 312: for ( language in listToArray( arguments.lang ) ) { 313: fileCopy( source="#this.luceeSourceUrl#/core/src/main/cfml/context/admin/resources/language/#language#.xml", 314: destination=this.workingDir & "#language#.xml" );315: }316: called from /Users/guustnieuwenhuis/Projects/Playground/lucee-admin-language-editor/webroot/components/LangEditorService.cfc: line 395 called from /Users/guustnieuwenhuis/Projects/Playground/lucee-admin-language-editor/webroot/ajaxApi/ajaxLangService.cfm: line 13
Java Stacktrace | lucee.runtime.exp.ApplicationException: Can't copy file [https://raw.githubusercontent.com/lucee/Lucee/6.0/core/src/main/cfml/context/admin/resources/language/nl.xml] to [/workingDir/nl.xml]  at java.base/java.io.UnixFileSystem.createFileExclusively(Native Method)  at java.base/java.io.File.createNewFile(File.java:1026)  at lucee.commons.io.res.type.file.FileResource.getOutputStream(FileResource.java:261)  at lucee.commons.io.res.util.ResourceSupport.copyTo(ResourceSupport.java:43)  at lucee.commons.io.IOUtil.copy(IOUtil.java:140)  at lucee.runtime.tag.FileTag.actionCopy(FileTag.java:586)  at lucee.runtime.functions.file.FileCopy.call(FileCopy.java:35)  at langeditorservice_cfc$cf.udfCall2(/components/LangEditorService.cfc:314)  at langeditorservice_cfc$cf.udfCall(/components/LangEditorService.cfc)  at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:112)  at lucee.runtime.type.UDFImpl._call(UDFImpl.java:350)  at lucee.runtime.type.UDFImpl.call(UDFImpl.java:223)  at lucee.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:786)  at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:787)  at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1775)  at langeditorservice_cfc$cf.udfCall2(/components/LangEditorService.cfc:395)  at langeditorservice_cfc$cf.udfCall(/components/LangEditorService.cfc)  at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:112)  at lucee.runtime.type.UDFImpl._call(UDFImpl.java:350)  at lucee.runtime.type.UDFImpl.call(UDFImpl.java:223)  at lucee.runtime.ComponentImpl._call(ComponentImpl.java:696)  at lucee.runtime.ComponentImpl._call(ComponentImpl.java:584)  at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1931)  at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:787)  at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1775)  at ajaxapi.ajaxlangservice_cfm$cf.call(/ajaxApi/ajaxLangService.cfm:13)  at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:1056)  at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:948)  at lucee.runtime.listener.ModernAppListener._onRequest(ModernAppListener.java:219)  at lucee.runtime.listener.MixedAppListener.onRequest(MixedAppListener.java:44)  at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2493)  at lucee.runtime.PageContextImpl._execute(PageContextImpl.java:2478)  at lucee.runtime.PageContextImpl.executeCFML(PageContextImpl.java:2449)  at lucee.runtime.engine.Request.exe(Request.java:45)  at lucee.runtime.engine.CFMLEngineImpl._service(CFMLEngineImpl.java:1216)  at lucee.runtime.engine.CFMLEngineImpl.serviceCFML(CFMLEngineImpl.java:1162)  at lucee.loader.engine.CFMLEngineWrapper.serviceCFML(CFMLEngineWrapper.java:97)  at lucee.loader.servlet.CFMLServlet.service(CFMLServlet.java:51)  at javax.servlet.http.HttpServlet.service(HttpServlet.java:590)  at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)  at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)  at org.cfmlprojects.regexpathinfofilter.RegexPathInfoFilter.doFilter(RegexPathInfoFilter.java:47)  at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)  at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)  at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)  at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)  at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)  at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)  at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)  at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132)  at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)  at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)  at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)  at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)  at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)  at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)  at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)  at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)  at runwar.Server$1.handleRequest(Server.java:531)  at io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52)  at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)  at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:269)  at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:78)  at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:133)  at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:130)  at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)  at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)  at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:249)  at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:78)  at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:99)  at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387)  at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:841)  at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)  at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019)  at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558)  at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1449)  at java.base/java.lang.Thread.run(Thread.java:832)
Timestamp | 1/24/23 8:26:38 AM CET

# screenshot

![CleanShot 2023-01-24 at 08 26 58](https://user-images.githubusercontent.com/523220/214234416-fa6a66c4-7ce1-4bf5-9848-2c598117fbd8.png)

**Comment by andreasRu** [comment]
Thanks for the report. This is the same issue another user reported, and it looks like the workingDir directory doesn't get created.

I've just updated/commited a fix that should make it work (Version 0.0.7). Could you please try it? 

Also, on what OS are you working? MacOS

**Comment by andreasRu** [comment]
This was fixed with 0.0.7. It's the same reported with https://github.com/andreasRu/lucee-admin-language-editor/issues/12

if the problem persists, please reopen the issue

**Comment by andreasRu** [comment]
Closing
