### ISSUE TITLE
add shortcut to search for text key in the admin on github 

### ISSUE THREAD

**Issue by zspitzer** [andreasRu/lucee-admin-language-editor#8]
it would be handy to be able to check where a text string is being used

like we do on lucee docs for test cases 

i.e https://github.com/search?q=application.AllowURLRequestTimeout+repo%3Alucee%2FLucee+path%3A%2Fcore%2Fsrc%2Fmain%2Fcfml%2Fcontext%2Fadmin%2F&type=Code&ref=advsearch&l=&l=

**Comment by andreasRu** [comment]
Perfect!!! Thanks, I was thinking of adding a cfcollection, but this looks much simpler.

**Comment by andreasRu** [comment]
I've added a simple button for a direct github search. See: https://github.com/andreasRu/lucee-admin-language-editor/commit/1ec0ee95fc97f47b84b4c91d0e679fbb8afbae5a
